global:
  images:
    tags:
      # You can override container names here using container name as a tag. Just replace '-' in container name to '_'. See example:
      #   contrail_external_kafka: "docker.io/opencontrailnightly/contrail-external-kafka:master-latest"
      dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    imagePullPolicy: "IfNotPresent"
    # Specify imageCredentials
    imageCredentials:
      # registry: quay.io
      # username: username
      # password: password

  contrail_env:
    CONTAINER_REGISTRY: docker.io/opencontrailnightly
    CONTRAIL_CONTAINER_TAG: master-latest
    CONTROLLER_NODES: 10.87.65.248
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin
    ANALYTICSDB_ENABLE: "true"
    ANALYTICS_ALARM_ENABLE: "true"
    ANALYTICS_SNMP_ENABLE: "true"

labels:
  analytics:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics_snmp:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"
  analytics_alarm:
    node_selector_key: opencontrail.org/controller
    node_selector_value: "enabled"


dependencies:
  analytics:
    daemonset:
    - contrail-config
  analytics_snmp:
    daemonset:
    - contrail-config
  analytics_alarm:
    daemonset:
    - contrail-config

# Names of secrets used by bootstrap and environmental checks
secrets:
  keystone:
    admin: contrail-analytics-keystone-admin

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  rabbitmq:
    auth:
      username: guest
      password: guest
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5673
    hosts:
      default: rabbitmq
    host_fqdn_override:
       default: null
    domain_override: null
  keystone:
    auth:
      username: admin
      password: password
      project_name: admin
      user_domain_name: default
      project_domain_name: default
      region_name: RegionOne
    hosts:
      default: keystone
    path:
      default: /v3
    port:
      api:
        default: 80
    scheme:
      default: http
    host_fqdn_override:
       default: null
    namespace: openstack

pod:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        analytics:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1

# Service related inputs are defined here
service:
  analytics_api_public_port: ""

# Ingress related inputs are defined here
# ingress:
#   analytics_api:
#     annotations:
#       kubernetes.io/ingress.class: nginx
#       nginx.ingress.kubernetes.io/rewrite-target: /
#     hosts:
#       - name: contrail-analytics-api
#         path: /
#       - name: contrail-analytics-api.contrail.svc.cluster.local
#         path: /

# VolumeMounts related inputs are defined here
volumeMounts:
  host_usr_bin:
    hostPath: '/usr/bin'

manifests:
  configmap_analytics_env: true
  configmap_analytics_keystone: true
  configmap_analytics_rabbitmq: true
  daemonset_analytics: true
  daemonset_analytics_snmp: true
  daemonset_analytics_alarm: true
  service_analytics_api_server: true
  service_analytics_api_ingress: true
  ingress_analytics_api: false
  secret_analytics_keystone_admin: true
